In [14]:
import numpy as np 
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [3]:
dataset = pd.read_csv(r"C:\Users\gtanu\Downloads\archive (4)\Financial Distress.csv")
dataset

Company  Time  Financial Distress      x1        x2       x3       x4  \
0           1     1            0.010636  1.2810  0.022934  0.87454  1.21640   
1           1     2           -0.455970  1.2700  0.006454  0.82067  1.00490   
2           1     3           -0.325390  1.0529 -0.059379  0.92242  0.72926   
3           1     4           -0.566570  1.1131 -0.015229  0.85888  0.80974   
4           2     1            1.357300  1.0623  0.107020  0.81460  0.83593   
...       ...   ...                 ...     ...       ...      ...      ...   
3667      422    10            0.438020  2.2605  0.202890  0.16037  0.18588   
3668      422    11            0.482410  1.9615  0.216440  0.20095  0.21642   
3669      422    12            0.500770  1.7099  0.207970  0.26136  0.21399   
3670      422    13            0.611030  1.5590  0.185450  0.30728  0.19307   
3671      422    14            0.518650  1.6148  0.176760  0.36369  0.18442   

            x5        x6       x7  ...      x74     x75      x76     x77  \
0     0.060940  0.188270  0.52510  ...   85.437   27.07   26.102  16.000   
1    -0.014080  0.181040  0.62288  ...  107.090   31.31   30.194  17.000   
2     0.020476  0.044865  0.43292  ...  120.870   36.07   35.273  17.000   
3     0.076037  0.091033  0.67546  ...   54.806   39.80   38.377  17.167   
4     0.199960  0.047800  0.74200  ...   85.437   27.07   26.102  16.000   
...        ...       ...      ...  ...      ...     ...      ...     ...   
3667  0.175970  0.198400  2.22360  ...  100.000  100.00  100.000  17.125   
3668  0.203590  0.189870  1.93820  ...   91.500  130.50  132.400  20.000   
3669  0.193670  0.183890  1.68980  ...   87.100  175.90  178.100  20.000   
3670  0.172140  0.170680  1.53890  ...   92.900  203.20  204.500  22.000   
3671  0.169550  0.197860  1.58420  ...   91.700  227.50  214.500  21.000   

       x78   x79  x80       x81  x82  x83  
0     16.0   0.2   22  0.060390   30   49  
1     16.0   0.4   22  0.010636   31   50  
2     15.0  -0.2   22 -0.455970   32   51  
3     16.0   5.6   22 -0.325390   33   52  
4     16.0   0.2   29  1.251000    7   27  
...    ...   ...  ...       ...  ...  ...  
3667  14.5  -7.0   37  0.436380    4   41  
3668  14.5 -16.0   37  0.438020    5   42  
3669  14.5 -20.2   37  0.482410    6   43  
3670  22.0   6.4   37  0.500770    7   44  
3671  20.5   8.6   37  0.611030    8   45  

[3672 rows x 86 columns]

In [4]:
dataset.describe()

Company         Time  Financial Distress           x1           x2  \
count  3672.000000  3672.000000         3672.000000  3672.000000  3672.000000   
mean    182.084423     7.528322            1.040257     1.387820     0.129706   
std     117.024636     4.064016            2.652227     1.452926     0.120013   
min       1.000000     1.000000           -8.631700     0.075170    -0.258080   
25%      80.000000     4.000000            0.172275     0.952145     0.048701   
50%     168.000000     7.000000            0.583805     1.183600     0.107530   
75%     264.250000    11.000000            1.351750     1.506475     0.188685   
max     422.000000    14.000000          128.400000    51.954000     0.749410   

                x3            x4           x5           x6           x7  ...  \
count  3672.000000  3.672000e+03  3672.000000  3672.000000  3672.000000  ...   
mean      0.615769  8.681599e-01     0.154949     0.106717     0.784031  ...   
std       0.177904  5.719519e-01     0.124904     0.210555     1.033606  ...   
min       0.016135  5.350000e-07    -0.269790    -0.627750     0.035160  ...   
25%       0.501888  5.525575e-01     0.070001    -0.027754     0.436003  ...   
50%       0.638690  7.752450e-01     0.131830     0.104325     0.641875  ...   
75%       0.749425  1.039000e+00     0.219570     0.231230     0.896772  ...   
max       0.967900  6.835600e+00     0.858540     0.929550    38.836000  ...   

               x74          x75          x76          x77          x78  \
count  3672.000000  3672.000000  3672.000000  3672.000000  3672.000000   
mean     86.839822    91.920506    89.115908    17.780855    15.198708   
std      16.706209    64.656504    64.349382     2.040152     2.828648   
min      54.806000    24.318000    23.776000    15.250000    12.000000   
25%      79.951000    39.800000    38.377000    16.000000    13.000000   
50%      90.000000    66.120000    59.471000    17.000000    14.500000   
75%      93.883000   130.500000   132.400000    20.000000    16.000000   
max     120.870000   227.500000   214.500000    22.000000    22.000000   

               x79          x80          x81          x82          x83  
count  3672.000000  3672.000000  3672.000000  3672.000000  3672.000000  
mean     -2.664305    19.714597     1.100488    13.122277    33.044935  
std       8.192663     7.508588     2.666733     9.465907    13.714563  
min     -20.200000     1.000000    -0.499220     1.000000     2.000000  
25%      -7.000000    14.000000     0.189912     6.000000    21.000000  
50%       0.200000    20.000000     0.594765    11.000000    34.000000  
75%       2.100000    26.000000     1.355050    17.000000    44.000000  
max       8.600000    37.000000   128.400000    49.000000    74.000000  

[8 rows x 86 columns]

In [5]:
dataset['Company'].unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [26]:
x_train = dataset.iloc[:,3:].values
y_train = dataset.iloc[:, 2].values
y_test = dataset.iloc[:, 2].values
x_test = dataset.iloc[:,3:].values
x_train

array([[ 1.2810e+00,  2.2934e-02,  8.7454e-01, ...,  6.0390e-02,
         3.0000e+01,  4.9000e+01],
       [ 1.2700e+00,  6.4542e-03,  8.2067e-01, ...,  1.0636e-02,
         3.1000e+01,  5.0000e+01],
       [ 1.0529e+00, -5.9379e-02,  9.2242e-01, ..., -4.5597e-01,
         3.2000e+01,  5.1000e+01],
       ...,
       [ 1.7099e+00,  2.0797e-01,  2.6136e-01, ...,  4.8241e-01,
         6.0000e+00,  4.3000e+01],
       [ 1.5590e+00,  1.8545e-01,  3.0728e-01, ...,  5.0077e-01,
         7.0000e+00,  4.4000e+01],
       [ 1.6148e+00,  1.7676e-01,  3.6369e-01, ...,  6.1103e-01,
         8.0000e+00,  4.5000e+01]])

In [29]:
y_train_binary = (y_train <= -0.50).astype(int)
y_test_binary = (y_test <= -0.50).astype(int)

In [30]:
my_obj = KNeighborsClassifier()
my_model = my_obj.fit(x_train, y_train_binary)
y_pred = my_model.predict(x_test)

ValueError: Found input variables with inconsistent numbers of samples: [2570, 3672]

In [13]:
accuracy = metrics.accuracy_score(y_test_binary, y_pred, normalize=True)
accuracy

0.9654139433551199

In [15]:
cm = confusion_matrix(y_pred, y_test_binary)
cf = classification_report(y_pred, y_test_binary)
print(cm)
print(cf)

[[3536  127]
 [   0    9]]
              precision    recall  f1-score   support

           0       1.00      0.97      0.98      3663
           1       0.07      1.00      0.12         9

    accuracy                           0.97      3672
   macro avg       0.53      0.98      0.55      3672
weighted avg       1.00      0.97      0.98      3672



In [27]:
y_binary = (y_train <= -0.50).astype(int)

In [28]:
x_train, x_test, y_train_binary, y_test_binary = train_test_split(x_test, y_binary, test_size=0.3, random_state=10)
knn = KNeighborsClassifier()
knn.fit(x_train, y_train_binary)
y_pred = knn.predict(x_test)

print("Accuracy:", metrics.accuracy_score(y_test_binary, y_pred))
print("F1 Score:", metrics.f1_score(y_test_binary, y_pred))

Accuracy: 0.9664246823956443
F1 Score: 0.13953488372093023
